# Generated by Django 5.1.6 on 2025-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
